version: '3.4'
networks: 
  ushort:
    external: true

services:
  db:
    image: postgres:14
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/migration://docker-entrypoint-initdb.d
    ports:
      - 5434:5432
    environment: 
      # - DATABASE_URL=postgres://db-user:db-password@tcp:5432/ushort?sslmode=disable"
      - POSTGRES_USER=db-user
      - POSTGRES_PASSWORD=db-password
    healthcheck:
      test: PGPASSWORD='db-password' psql -U db-user --command='SELECT 1'
      interval: 1s
      timeout: 2s
      retries: 5
    networks: 
      - ushort
 
  # flyway:
  #   image: flyway/flyway:latest
  #   command: -url=jdbc:postgresql://db:5432/ushort -user=db-user -password=db-password migrate
  #   volumes: 
  #     - :/flyway/sql
  #   depends_on: 
  #     - db
  #   networks: 
  #     - ushort

  ushort:    
    image: aleksandrmac/ushort:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
      # - 8001:8001
    environment: 
      - JAEGER_AGENT_HOST="jaeger"
      - JAEGER_AGENT_PORT=6831
      - SERVER_PORT=8000
      - SERVER_TIMEOUT=30
      # - DB_DRIVER=postgres
      # - DB_NAME=ushort
      # - DB_HOST=localhost
      # - DB_PASSWORD=unset
      # - DB_SSLMODE=disable
      # - DB_TIMEZONE=Asia/Yakutsk
      - DATABASE_URL=postgres://db-user:db-password@db:5432/ushort?sslmode=disable
    working_dir: /
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-async-connect: "true"
    #     fluentd-address: localhost:24224
    #     tag: ushort
    volumes:
      - ./internal/secrets:/internal/secrets
    depends_on: 
      - db
      # - flyway
    networks: 
      - ushort

  pgadmin:
    image: dpage/pgadmin4
    # volumes: 
    #   - ./db/pgadmin4:/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=k-t_monkey@mail.ru
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - 8080:8080
    networks: 
      - ushort
  
  # prometheus:
  #   image: prom/prometheus:v2.25.0
  #   volumes:
  #     - ./deployments/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml 
  #     - ./deployments/prometheus/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml
  #   ports:
  #     - 9090:9090
  #   depends_on:
  #     - ushort
  #   networks: 
  #     - ushort
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16685:16685"
      - "16686:16686"
    networks: 
      - ushort


